### ISSUE TITLE
[APPLICATION] sario528

### ISSUE THREAD

**Issue by sario528** [quirc-bot/Project-Takeover#1]
My Miraheze and Freenode username is sario528, I am a beginner level dev learning Python as my first programming language. I am willing to hold the repo in the absence of a more experienced dev and would be willing to turn over the repo if another dev wanted to take on the project.

**Comment by RhinosF1** [comment]
Thanks for applying!

**Comment by RhinosF1** [comment]
Passed

**Comment by RhinosF1** [comment]
All done
